# fly.toml app configuration file generated for tg-solana-bot on 2025-01-09T12:00:00Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "tg-solana-bot"
primary_region = "cdg"

[build]

[env]
  PYTHONUNBUFFERED = "1"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[machine]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

[processes]
  app = "python main.py"
